AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance and output its public IP address

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ed90a3b5bde5e371 # Specify your desired Amazon Machine Image (AMI) ID
      InstanceType: t2.micro  # Specify your desired instance type
      KeyName: Practice_KP # Specify the key pair to use for SSH access
      SecurityGroups:
        - Ref: mySecurityGroup  # Reference to the security group
      AvailabilityZone: ca-central-1a
      Tags:
         - Key: Name
           Value: MyEC2InstanceName     

  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Open SSH access to all IP addresses (for demo purposes)
